### ISSUE TITLE
Performance on Gated2Depth model

### ISSUE THREAD

**Issue by amanwalia123** [gruberto/PixelAccurateDepthBenchmark#2]
Hi Tobias,

I am curious if you have tried the Gated2Depth model on gated images given for this dataset. I seem to have issues with obtaining the correct depth using the pre-trained model for gated2depth.

Thanks,

**Comment by gruberto** [comment]
Hi. The gated images in the Pixel-Accurate Depth Benchmark are acquired with different range-intensity profiles because the length of the fogchamber is quite limited (< 30m). Therefore, the Gated2Depth model does not work on those images. There will be a paper published at the ATZ Automated Driving (https://www.atzlive.de/en/events/automated-driving/) this October that deals with the adaptation of the Gated2Depth model to the new range-intensity profiles in the fogchamber. Best, Tobias

**Comment by amanwalia123** [comment]
Thanks, your explanation is really helpful.

**Comment by anupamsobti** [comment]
@gruberto Is this why radar data is also not available for this?

**Comment by gruberto** [comment]
For this dataset we have not recorded radar data because the fogchamber is mainly a metal construction and the data won't be that helpful.

**Comment by anupamsobti** [comment]
I understand. Thank you.
