### ISSUE TITLE
Inquiry on the dataset

### ISSUE THREAD

**Issue by yuanziii** [gruberto/PixelAccurateDepthBenchmark#5]
Hi Tobias,

Thanks for your fantastic work! Recently I want to use the dataset to run some experiments on depth completion. Thus I need sparse lidar depth, corresponding image, and annotated depth map. I downloaded the dataset and the folder "rgb_left_8bit" I believe contains the color images, but may I check which folder contains the corresponding sparse lidar readings and dense depth map?

Thanks and best Regards

**Comment by gruberto** [comment]
The section [Sensor Setup](https://github.com/gruberto/PixelAccurateDepthBenchmark#sensor-setup) in the `README.md` of this repository contains all information about how to load the sparse lidar depth, corresponding image and annotated depth map.

**Comment by yuanziii** [comment]
Thanks for your prompt reply.

my confusion comes from that both the rgb and sparse lidar have 10 frames for each scene and each weather, may I know whether all of these correspond with the same scene1 for groundtruth? So that for each scene there is only 1 ground truth.

Thanks for your kind answer!

**Comment by gruberto** [comment]
There are 10 frames for each scene for the measuring sensors (camera and lidar) in order to include multiple measurements of the same scene. However, the ground truth for a single scene was only acquired once because this measurement was very cumbersome and cannot be done in real-time. I hope I could help you!
